name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: {{ runs_on }}
    steps:
      - name: Print greeting
        run: echo "hello world!"
        with:
          account_id: "{{ aws_account_id }}"
      - name: Print goodbye
        run: echo "done bye!"
