name: First Workflow
on: workflow_dispatch
# This file
# should have 
jobs: # lot of comments
  first-job:
    runs-on: "ubuntu-latest"
    steps:
      - name: Print greeting
        run: echo "hello world!"
        with:
          account_id: "{{ aws_account_id }}"
      - name: Print goodbye
        run: echo "done bye!"
